### ISSUE TITLE
Twitter behavior is confusing, improvements

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#29]
Hi @webcolor-in our users are still saying that using this on Twitter is confusing, since if you just click the Our.News icon (not one attached to an article), it comes back with the below screen:

<img width="1170" alt="Screen Shot 2019-10-17 at 9 28 49 AM" src="https://user-images.githubusercontent.com/35204816/67013439-1dc03180-f0c1-11e9-90f8-fdee6232c717.png">

Can you please change this, so that if the user is on Twitter and opens the icon from the menu bar, instead of displaying the "Data on this publisher is not available" error, display:

**How to use our extension on Twitter:**

Instead of clicking the purple Our.News icon in the menu bar, look for the icon attached to individual tweets themselves-- usually these are only available for tweets that include links to news articles. Click to open the Nutrition Label for that particular tweet.

**Comment by rkzack** [comment]
Also, please make the same change for Facebook.

- [ ] Change default Twitter open message when not used on an individual post
- [ ] Change default Facebook open message when not used on an individual post

**Comment by webcolor-in** [comment]
Estimate - 2 hours

**Comment by webcolor-in** [comment]
I will change wording `tweets` `facebook posts`

**Comment by rkzack** [comment]
Ok to proceed on this.

**Comment by webcolor-in** [comment]
There is an edge case here - Some one can open this extension from icon click in menu bar and we show this message but then they can click on any icon from tweet or facebook page which results in no publisher data and now ideally our message should refresh to what it was than educating user. What should I do in that case?

**Comment by rkzack** [comment]
You may be over-thinking this.  It only needs to display the new message when the icon is clicked in the menu bar and only when on Facebook or Twitter. Otherwise it should behave as it did before.

**Comment by webcolor-in** [comment]
All I meant is we can't replace message but got to retain old message and switch when needed. Its almost done no problem.

**Comment by webcolor-in** [comment]
Done

**Comment by rkzack** [comment]
Thank you but two more issues on this:

1). On Twitter, after logging in using the separate window, after going back to Twitter, it still thinks the user is not logged in, and tries to force them to login again. You have to manually refresh the page. Can you add an extra logintest or some other method so that it will detect the login?

2). On Facebook, it's not displaying the message at all, instead is saying "Oops, this URL is not eligible to be indexed". It should display the "How to use our extension on Facebook:" message.

<img width="386" alt="Screen Shot 2019-10-19 at 10 41 31 AM" src="https://user-images.githubusercontent.com/35204816/67146864-5e54b200-f25d-11e9-957b-30565d12c72f.png">

**Comment by webcolor-in** [comment]
On point 2 - This is coming from backend as facebook URL is excluded one but not twitter. If this exclusion is removed in configurations it should show right message.

**Comment by rkzack** [comment]
We can't remove the exclusion so please build logic to work around it.

**Comment by webcolor-in** [comment]
Point 1 - I added quick refresh so it should pick user login version now.

**Comment by webcolor-in** [comment]
Exclusion happens much early so that needs to be altered. Estimate: 3 hours

**Comment by rkzack** [comment]
3 hours here also seems very, very high---  all Im asking for is a simple if/then statement -- 

If Facebook then display "How to use" instead of "Oops this URL"

Should take you 15 minutes.

**Comment by rkzack** [comment]
Point 1 -- yes the quick refresh is working, thanks

**Comment by webcolor-in** [comment]
No ways I can do this in 15 minutes. I am not Rich :)

The earlier task I took to show instruction in twitter and fb took me nearly 4 hours (estimate was 2 hours) as I had to create 2 different version of text and retain both/switch as needed.

**Comment by rkzack** [comment]
Are you billing us based on the actual time you spend, or just making up numbers?

**Comment by rkzack** [comment]
Please add an if/then statement to show the "How to use" message instead of the "Oops this URL" message on Facebook. Please explain how this will take more than 15 minutes.

And please start testing more thoroughly-- you're adding more bugs with every bug you fix.

**Comment by webcolor-in** [comment]
1 - It should check how the popup was opened, if its due to icon click in task bar or facebook post
2 - It should check if the current site is social which use to happen after but need to be done before 
3 - Now it should replace text or better is to hide/show message because we avoid putting text changes in javascript

Done in right way the task does take time. I never charge you by throwing numbers but when its urgent I try to fix quickly and fix it later giving time as priority. And when business logic is changing the way extension processes data and passes this data change, its better done giving some time and test it. What I feel is its not important even if I make 2 line change in 2 hour but its more important that I maintain system that is flexible and is open to take more.

**Comment by rkzack** [comment]
Some pseudo-code for you:

if (popup_is_opened_by_facebook_post) && display_oops_error_is_true  
then display_How_to_use_error()  
else
display_oops_error

**Comment by webcolor-in** [comment]
> Some pseudo-code for you:
> 
> if (popup_is_opened_by_facebook_post) && display_oops_error_is_true
> then display_How_to_use_error()
> else
> display_oops_error

That's okay I can figure things out. Fix done, code pushed.

**Comment by rkzack** [comment]
This is working great for Facebook, thank you. But, it's still not working for Twitter.

**Comment by webcolor-in** [comment]
Done

**Comment by webcolor-in** [comment]
The response I am getting from API for twitter.com & mobile.twitter.com is different so it isn't showing newstrition automatically when its twitter.com. I tested mobile.twitter.com which is what was shows as default in your machine and it properly shows message.
![Annotation 2019-10-20 222912](https://user-images.githubusercontent.com/55145799/67163215-e9cb6180-f389-11e9-8bf7-6973a480ce77.png)

**Comment by rkzack** [comment]
I don't know how else to help you fix this issue-- it's still not working for us on Twitter, and so we're still stuck and cannot launch this latest version. Maybe test a few different scenarios yourself to see the problem?  Or just do as I've requested in the other ticket and force it to always display the "How to use our extension on Twitter" if you try to open the extension using the menu bar icon on Twitter instead of on an individual Tweet.

**Comment by webcolor-in** [comment]
I will add fix so it shows same as facebook.

**Comment by webcolor-in** [comment]
We can close this as its duplicate chat of another thread.
