### ISSUE TITLE
Bug, Q&A not resetting between uses on Twitter and FB

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#34]
Hi @webcolor-in we found a bug-- if you complete a Q&A sequence on one article on Twitter or FB, on all subsequent articles it just says "Thank you for your feedback" and it's not loading the new questions for the new article. Please fix, thank you.

**Comment by webcolor-in** [comment]
Fixed

**Comment by rkzack** [comment]
The Q&A section is back, but it's still showing the "Thank you for your feedback!" message underneath the questions on the 2nd and subsequent uses, see below.

![Screen Shot 2019-10-21 at 8 27 32 AM](https://user-images.githubusercontent.com/35204816/67204985-b82fb600-f3dc-11e9-9e87-5a41601b782f.png)

**Comment by webcolor-in** [comment]
Fixed

**Comment by rkzack** [comment]
Ok, this is working now, thank you. Closing issue.
